### ISSUE TITLE
Make packageName variable available in template recipe

### ISSUE THREAD

**Issue by horseunnamed** [hhru/android-multimodule-plugin#29]
Не хватает возможности использовать packageName в выражениях рецепта. 
Два возможных сценария использования. 

1. Делать так: 
```
  - predicate:
      validIf: ${needTests}
      commands:
        - mkDirs:
            - ${rootOut}:
                - test:
                    - java:
                        - ${packageName}
```

2. Объявлять globals для вложенных пакетов, для сокращения бойлерплейта в шаблонах. Например, делать
`package ${modelPackage}`
вместо того, чтобы каждый раз писать
`package ${packageName}.${fragmentPackage}.model`
