### ISSUE TITLE
Шаблон не генерируется

### ISSUE THREAD

**Issue by Natkarock** [hhru/android-multimodule-plugin#32]
Если в файл рецепта добавить генерацию xml файла ресурса, то после ввода имен параметров, не происходит генерация ни одного файла  Без генерации xml файла все проходит без проблем. Побовала генерацию вашего шаблона https://github.com/hhru/android-style-guide/tree/master/tools/geminio/templates/Cell .Также не генерируется 

Android Studio 4.1.2

Привожу файл рецепта:

```
requiredParams:
  name: Viper BaseModule
  description: Creates Viper BaseModule

widgets:
  - stringParameter:
      id: appPackageName
      name: Package Name
      help: The name of the fragment class to create
      constraints:
        - nonempty
        - unique
      default: com

  - stringParameter:
      id: appClassName
      name: Application Class Name
      help: The name of the fragment class to create
      constraints:
        - class
        - nonempty
        - unique
      default: Application

  - stringParameter:
      id: baseClassName
      name: Fragment Name
      help: The name of the fragment class to create
      constraints:
        - class
        - nonempty
        - unique
      default: Blank


  - stringParameter:
      id: fragmentLayoutName
      name: Fragment Layout Name
      help: The name of the layout to create
      constraints:
        - layout
        - nonempty
        - unique
      default: fragment
      suggest: fragment_${baseClassName.classToResource()}



recipe:
  - mkDirs:
    - ${srcOut}:
      - data
      - di
    - ${resOut}:
      - layout
  - instantiateAndOpen:
      from: root/src/app_package/Fragment.kt.ftl
      to: ${srcOut}/${baseClassName}Fragment.kt

  - instantiate:
      from: root/res/layout/fragment.xml.ftl
      to: ${resOut}/layout/${fragmentLayoutName}.xml

  - instantiate:
      from: root/src/app_package/Contract.kt.ftl
      to: ${srcOut}/${baseClassName}Contract.kt

  - instantiate:
      from: root/src/app_package/Interactor.kt.ftl
      to: ${srcOut}/${baseClassName}Interactor.kt

  - instantiate:
      from: root/src/app_package/Router.kt.ftl
      to: ${srcOut}/${baseClassName}Router.kt

  - instantiate:
      from: root/src/app_package/Presenter.kt.ftl
      to: ${srcOut}/${baseClassName}Presenter.kt

  - instantiate:
      from: root/src/app_package/di/Component.kt.ftl
      to: ${srcOut}/di/${baseClassName}Component.kt

  - instantiate:
      from: root/src/app_package/di/Module.kt.ftl
      to: ${srcOut}/di/${baseClassName}Module.kt

  - instantiate:
      from: root/src/app_package/data/Repo.kt.ftl
      to: ${srcOut}/data/${baseClassName}Repo.kt
```
