### ISSUE TITLE
Availability не работает

### ISSUE THREAD

**Issue by AlexeyKorshun** [hhru/android-multimodule-plugin#41]
в рецепте ставлю availability: false и виджет скрывается, вместо того что бы стать недоступным для редактирования

**Comment by PStrelchenko** [comment]
@AlexeyKorshun , привет!
А приведи, пожалуйста, весь рецепт, который ты пытаешься запустить? Очень поможет в отладке.

**Comment by AlexeyKorshun** [comment]
```
requiredParams:
  name: name
  description: description

optionalParams:
  revision: 1
  category: fragment
  formFactor: mobile
  constraints:
    - kotlin
  screens:
    - fragment_gallery
    - menu_entry
  minApi: 21
  minBuildApi: 21

widgets:
  - stringParameter:
      id: className
      name: Screen Name Prefix
      help: The name of the Screen to create
      constraints:
        - class
        - nonempty
        - unique
      default: Blank

  - stringParameter:
      id: fragmentName
      name: Fragment Name
      help: The name of the Fragment class to create
      constraints:
        - class
        - nonempty
        - unique
      default: BlankFragment
      suggest: ${className}Fragment
      visibility: true
      availability: false
```
