### ISSUE TITLE
Не работает команда addGradlePlugin в predicate

### ISSUE THREAD

**Issue by pavel163** [hhru/android-multimodule-plugin#52]
Пытаюсь сделать вот так:
```yaml
  - predicate:
      validIf: ${needKotlinSerialization}
      commands:
        - addGradlePlugins:
            - kotlinx.serialization
 ```

Но плагин не добавляется
